# Zotero ID, SMTP，LLM API相关配置去除，在github secrets中设置

# Zotero配置
ZOTERO_IGNORE: |
  # 使用gitignore风格的语法指定要忽略的Zotero文件夹
  # 例如：
  Blog/Copley
  Blog/Copley/**
  AutonomousDriving
  AutonomousDriving/**
  !AutonomousDriving/End-to-End
  CV
  CV/**
  Conferences
  paper_with_code
  Paper_with_code/**
  Training_Methodology
  Training_Methodology/**

# Arxiv查询配置
ARXIV_QUERY: "cs.AI+cs.CV+cs.LG+cs.CL+cs.RO"  # 目标arxiv论文类别
ARXIV_QUERY_KEYWORD: |
  Embodied Agent, Robot Manipulation, Robotic Manipulation, 
  Robot Navigation, Grasping, Robot Learning, 
  Vision-Language-Action Model, Vision Language Action Model, 
  Reinforcement Learning, Imitation Learning


# 可选配置
MAX_PAPER_NUM: 10  # 邮件中展示的最大论文数量，-1表示展示所有论文
SEND_EMPTY: false  # 是否在没有新论文时发送空邮件

# LLM推荐算法配置
LLM_RECOMMENDER:
  # 研究兴趣领域
  RESEARCH_INTERESTS:
    - "embodied AI"
    - "robotics"
    - "world model" 
    - "multimodal learning"
    - "vision-language models"
    - "robot learning"
    - "reinforcement learning"
    - "natural language processing"
    - "robot manipulation"
    - "robot navigation"
    - "imitation learning"
    - "robot grasp"
    - "vision-language-action model"
  
  # 批处理配置
  CORPUS_BATCH_SIZE: 20  # 用于参考的历史论文数量
  CANDIDATE_BATCH_SIZE: 20  # 每批处理的候选论文数量
  
  # 评分配置
  KEYWORD_BONUS: 1.0  # 关键词匹配论文的额外加分
  DEFAULT_SCORE: 5.0  # API调用失败时的默认分数