# Zotero配置
ZOTERO_IGNORE: |
  Blog/Copley
  Blog/Copley/**
  AutonomousDriving
  AutonomousDriving/**
  !AutonomousDriving/End-to-End
  CV
  CV/**
  Conferences
  paper_with_code
  Paper_with_code/**
  Training_Methodology
  Training_Methodology/**

# Arxiv查询配置
ARXIV_QUERY: "cs.AI+cs.CV+cs.LG+cs.CL+cs.RO"  # 目标arxiv论文类别
ARXIV_QUERY_KEYWORD: |
  Embodied Agent, Robot Manipulation, Robotic Manipulation, 
  Robot Navigation, Grasping, Robot Learning, 
  Vision-Language-Action Model, Vision Language Action Model, 
  Reinforcement Learning, Imitation Learning


# 可选配置
MAX_PAPER_NUM: 15  # 邮件中展示的最大论文数量，-1表示展示所有论文
SEND_EMPTY: false  # 是否在没有新论文时发送空邮件

# LLM推荐算法配置
LLM_RECOMMENDER:
  # 研究兴趣领域
  RESEARCH_INTERESTS:
    - "embodied AI"
    - "robotics"
    - "world model" 
    - "embodied dataset"
    - "robot dataset"
    - "vision-language models"
    - "robot learning"
    - "reinforcement learning"
    - "robot manipulation"
    - "robot navigation"
    - "imitation learning"
    - "robot grasp"
    - "vision-language-action model"
  
  # 批处理配置
  CORPUS_BATCH_SIZE: 20  # 用于参考的历史论文数量
  CANDIDATE_BATCH_SIZE: 20  # 每批处理的候选论文数量
  
  # 评分配置
  KEYWORD_BONUS: 0.5  # 关键词匹配论文的额外加分
  DEFAULT_SCORE: 5.0  # API调用失败时的默认分数
  
  # 文本处理配置
  ABSTRACT_MAX_LENGTH: 500  # 摘要最大长度限制
  SCORE_FILTER_THRESHOLD: 5.0  # 论文评分过滤阈值
  MAX_SCORE_LIMIT: 10.0  # 最大评分限制
  SCORE_SCALE_FACTOR: 10.0  # 传统方法的评分缩放因子
  
  # API调用和限流配置
  MAX_REQUESTS_PER_MINUTE: 9  # 每分钟最大请求数（针对Gemini）
  API_RETRY_ATTEMPTS: 3  # API调用失败时的重试次数
  API_RETRY_DELAY: 3.0  # 重试间隔时间（秒）
  RATE_LIMIT_BUFFER: 1.0  # 限流缓冲时间（秒）
  
  # 传统推荐配置
  EMBEDDING_MODEL: "avsolatorio/GIST-small-Embedding-v0"  # 嵌入模型
  USE_TIME_DECAY: true  # 是否使用时间衰减权重
